# Use root/example as user/password credentials
version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: web:latest
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    container_name: mongodb_bs
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb_network
